steps:
  # 1. Install dependencies
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'backend/requirements.txt', '--user']

  # 2. Run tests
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'backend/']

  # 3. Deploy to Cloud Run
  # This step deploys the container image to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ai-product-manager-backend' # Your Cloud Run service name
      - '--source=./backend'
      - '--platform=managed'
      - '--region=asia-northeast1' # Your service region
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'
      # Pass secrets as environment variables
      - '--update-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,CORPORATE_API_KEY=CORPORATE_API_KEY:latest' # <--- 変更点
    secretEnv: ['GEMINI_API_KEY', 'CORPORATE_API_KEY'] # <--- 変更点

# Define the secrets to be used in the build steps.
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/CORPORATE_API_KEY/versions/latest # <--- 変更点
    env: 'CORPORATE_API_KEY'